version: '3.8'

networks:
  sdp_next:
    name: sdp_next
    driver: overlay
    attachable: true

volumes:
  data:
    driver: local
  tmp:
    driver: local

services:
  node:
    image: $DOCKER_IMAGE
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 10s
    environment:
      ALLOWED_ORIGINS: https://catalogue.saeon.dvn
      API_ADDRESS: https://catalogue.saeon.dvn
      APP_KEY: $APP_KEY
      CURATOR_CONTACT: $CURATOR_CONTACT
      DEFAULT_ADMIN_EMAIL_ADDRESSES: $DEFAULT_ADMIN_EMAIL_ADDRESSES
      DEFAULT_SYSADMIN_EMAIL_ADDRESSES: $DEFAULT_SYSADMIN_EMAIL_ADDRESSES
      DEPLOYMENT_ENV: production
      DOCKER_DATA_VOLUME: sdp_next_data
      DOCKER_NETWORK: sdp_next
      DOCKER_TMP_VOLUME: sdp_next_tmp
      ELASTICSEARCH_ADDRESS: http://next.elasticsearch.saeon.int
      HOSTNAME: https://catalogue.saeon.dvn
      LOG_QUERY_DETAILS: 'false'
      SAEON_ODP_INTEGRATION_SCHEDULE: '0 0 2 * * *'
      SITEMAP_INTEGRATION_SCHEDULE: '0 0 2 * * *'
      MONGO_DB_ADDRESS: mongodb://mongo.saeon.int:27117
      MONGO_DB_PASSWORD: $MONGO_DB_PASSWORD
      MONGO_DB_USERNAME: $MONGO_DB_USERNAME
      MONGO_DB: sdp_next
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      ODP_ADDRESS: https://odp.saeon.dvn
      ODP_AUTH_SCOPES: 'ODP.Catalogue'
      ODP_CLIENT_SECRET: $ODP_CLIENT_SECRET
      ODP_FILTER_PATH: /app/odp-filter.js
      CLIENT_FILTER_CONFIG_PATH: /app/client-filters.json
      ODP_SSO_CLIENT_ID: $ODP_SSO_CLIENT_ID
      ODP_SSO_CLIENT_SCOPES: 'openid SAEON.DataPortal'
      ODP_SSO_CLIENT_SECRET: $ODP_SSO_CLIENT_SECRET
      TECHNICAL_CONTACT: $TECHNICAL_CONTACT
      TZ: utc
    ports:
      - 6003:3000
    volumes:
      - tmp:/tmp/sdp-data
      - data:/var/lib/sdp-data
    networks:
      - sdp_next
