version = 0.1

extensions = ['chomp@0.1:prettier']

[[task]]
name = 'build'
run = """
  rm -rf api/src/clients
  chomp -c clients build
  mv clients/dist api/src/clients
"""

# REPOSITORY TOOLING

[[task]]
name = 'doc'
run = '''
  doctoc README.md
  doctoc **/README.md
'''

[[task]]
name = 'git:configure'
run = 'git config --local include.path ../.gitconfig'

[[task]]
name = 'git:add-all'
run = 'git add .'

[[task]]
name = 'prepare'
run = 'husky install'

[[task]]
name = 'prettier'
template = 'prettier'
[task.template-options]
ignore-path = '.prettierignore'
files = '**/*.@(js|jsx|json|mjs|cjs|graphql|yml)'
loglevel = 'log'
config = '.prettierrc'

[[task]]
name = 'prettier:changed'
run = 'pretty-quick'

[[task]]
name = 'reset'
run = """
rm -rf node_modules
find . \
  -name node_modules \
  -type d \
  -exec rm -rv {} + \
    && find . \
      -name package-lock.json \
      -type f \
      -delete
"""