version = 0.1

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = 'ncu -u'

# REPOSITORY TOOLING

[[task]]
name = 'doc'
run = '''
  doctoc README.md
  doctoc src/**/README.md
'''

[[task]]
name = 'git:configure'
run = 'git config --local include.path ../.gitconfig'

[[task]]
name = 'git:add-all'
run = 'git add .'

[[task]]
name = 'prepare'
run = 'husky install'

[[task]]
name = 'prettier'
run = 'prettier --write "./**/*.@(js|jsx|json|mjs|cjs|graphql|yml)"'

[[task]]
name = 'prettier:changed'
run = 'pretty-quick'

[[task]]
name = 'lint'
deps = [
  'lint:api',
  'lint:client',
]

[[task]]
name = 'lint:api'
run = 'chomp lint -c src/api/chompfile.toml'

[[task]]
name = 'lint:client'
run = 'chomp lint -c src/clients/chompfile.toml'

# DEPENDENCY MANAGEMNT

[[task]]
name = 'clean-deps'
run = 'find . -name node_modules -type d -exec rm -rv {} + && find . -name package-lock.json -type f -delete'


# PACKAGES

[[task]]
name = 'pkgs:build'
run = '''
  chomp build -c src/packages/cli-tools/chompfile.toml
  chomp build -c src/packages/graphql-iterator/chompfile.toml
  chomp build -c src/packages/logger/chompfile.toml
'''