version = 0.1

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = 'ncu -u'

# START SCRIPTS

[[task]]
name = 'start:api'
run = 'chomp start -c src/api/chompfile.toml'

[[task]]
name = 'start:clients'
run = 'chomp start -c src/clients/chompfile.toml'

[[task]]
name = 'start:proxy'
run = 'chomp start -c src/proxy/chompfile.toml'

# REPOSITORY TOOLING

[[task]]
name = 'doc'
run = '''
  doctoc README.md
  doctoc src/clients/README.md
  doctoc src/api/README.md
  doctoc src/proxy/README.md
  doctoc src/clients/tests/README.md
'''

[[task]]
name = 'git:configure'
run = 'git config --local include.path ../.gitconfig'

[[task]]
name = 'git:add-all'
run = 'git add .'

[[task]]
name = 'prepare'
run = 'husky install'

[[task]]
name = 'prettier'
run = 'prettier --write "./**/*.@(js|jsx|json|mjs|cjs|graphql|yml)"'

[[task]]
name = 'prettier:changed'
run = 'pretty-quick'

[[task]]
name = 'lint'
deps = [
  'lint:api',
  'lint:client',
  'lint:proxy'
]

[[task]]
name = 'lint:api'
run = 'chomp lint -c src/api/chompfile.toml'

[[task]]
name = 'lint:client'
run = 'chomp lint -c src/clients/chompfile.toml'

[[task]]
name = 'lint:proxy'
run = 'chomp lint -c src/proxy/chompfile.toml'

# DEPENDENCY MANAGEMNT

[[task]]
name = 'clean-deps'
run = 'find . -name node_modules -type d -exec rm -rv {} + && find . -name package-lock.json -type f -delete'

[[task]]
name = 'ncu:all'
run = '''
  chomp ncu
  chomp ncu -c src/api/chompfile.toml
  chomp ncu -c src/clients/chompfile.toml
  chomp ncu -c src/proxy/chompfile.toml
'''

[[task]]
name = 'ncu-u:all'
run = '''
  chomp ncu:u
  chomp ncu:u -c src/api/chompfile.toml
  chomp ncu:u -c src/clients/chompfile.toml
  chomp ncu:u -c src/proxy/chompfile.toml
'''

[[task]]
name = 'deps:install'
run = '''
  npm install
  npm --prefix src/api install
  npm --prefix src/clients install --force
  npm --prefix src/proxy install
  npm --prefix src/packages/cli-tools install
  npm --prefix src/packages/graphql-iterator install --force
  npm --prefix src/packages/logger install
'''

[[task]]
name = 'deps:update'
serial = true
deps = ['ncu-u:all', 'deps:install']

# PACKAGES

[[task]]
name = 'pkgs:build'
run = '''
  chomp build -c src/packages/cli-tools/chompfile.toml
  chomp build -c src/packages/graphql-iterator/chompfile.toml
  chomp build -c src/packages/logger/chompfile.toml
'''

[[task]]
name = 'pkgs:publish:major'
env = { TC='utc' }
deps = ['pkgs:build']
run = 'node scripts/publish-all.js -s major'

[[task]]
name = 'pkgs:publish:minor'
env = { TC='utc' }
deps = ['pkgs:build']
run = 'node scripts/publish-all.js -s minor'

[[task]]
name = 'pkgs:publish:patch'
env = { TC='utc' }
deps = ['pkgs:build']
run = 'node scripts/publish-all.js -s patch'