version: '3.7'

services:
  # atlas-redis-dev:
  #   container_name: atlas-redis-dev
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - 6379:6379

  atlas-mongodb-dev:
    container_name: atlas-mongodb-dev
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017

  atlas-anyproxy-dev:
    container_name: atlas-anyproxy-dev
    restart: always
    build:
      context: .
      dockerfile: src/@saeon/anyproxy/Dockerfile
    ports:
      - 8001:8001
      - 8002:8002

  atlas-api-dev:
    container_name: atlas-api-dev
    restart: always
    build:
      context: .
      dockerfile: src/@saeon/atlas-api/Dockerfile
    ports:
      - 5000:3000

  atlas-client-dev:
    container_name: atlas-client-dev
    restart: always
    build:
      context: .
      dockerfile: src/@saeon/atlas-client/Dockerfile
    ports:
      - 5001:80
