version: '3.8'

volumes:
  mongo:
    driver: local
  elasticsearch:
    driver: local
  postgis:
    driver: local

services:
  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: $ELASTICSEARCH_IMAGE
    environment:
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    restart: always
    image: $KIBANA_IMAGE
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  mongo:
    container_name: mongo
    restart: always
    image: $MONGO_IMAGE
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PSWD
    volumes:
      - mongo:/data/db/
    ports:
      - 27017:27017

  postgis:
    image: $POSTGIS_IMAGE
    container_name: postgis
    environment:
      POSTGRES_USER: $POSTGIS_USER
      POSTGRES_PASSWORD: $POSTGIS_PSWD
      POSTGRES_DB: catalogue
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5442:5432
    volumes:
      - postgis:/var/lib/postgresql/data/pgdata

  proxy:
    container_name: proxy
    restart: always
    build:
      context: src/services/proxy
      dockerfile: Dockerfile
      args:
        ELASTICSEARCH_PROXY: $ELASTICSEARCH_PROXY
        LATEST_COMMIT: $LATEST_COMMIT
    ports:
      - 8001:8001
      - 8002:8002
    depends_on:
      - elasticsearch

  api:
    container_name: api
    restart: always
    build:
      context: src/services/api
      dockerfile: Dockerfile
      args:
        MONGO_USER: $MONGO_USER
        MONGO_PSWD: $MONGO_PSWD
        POSTGIS_USER: $POSTGIS_USER
        POSTGIS_PSWD: $POSTGIS_PSWD
        POSTGIS_FOREIGN_USER: $POSTGIS_FOREIGN_USER
        POSTGIS_FOREIGN_PASSWORD: $POSTGIS_FOREIGN_PASSWORD
    ports:
      - 5000:3000
    depends_on:
      - proxy
      - mongo
      - elasticsearch
      - postgis

  client:
    container_name: client
    restart: always
    build: src/services/client
    ports:
      - 5001:80
    depends_on:
      - api
