version: '3.7'

services:
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - 6379:6379

  anyproxy:
    network_mode: host
    container_name: atlas-anyproxy-dev
    restart: always
    build:
      context: .
      dockerfile: src/@saeon/anyproxy/Dockerfile
    ports:
      - 8001:8001
      - 8002:8002

  atlas-api-dev:
    network_mode: host
    container_name: atlas-api-dev
    restart: always
    build:
      context: .
      dockerfile: src/@saeon/atlas-api/Dockerfile
    ports:
      - 5000:3000

  atlas-client-dev:
    container_name: atlas-client-dev
    restart: always
    build:
      context: .
      dockerfile: src/@saeon/atlas-client/Dockerfile
    ports:
      - 5001:80
