version: '3.7'

volumes:
  mongo:

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PSWD}
    volumes:
      - mongo:/data/db/
    ports:
      - 27017:27017

  proxy:
    container_name: proxy
    restart: always
    build:
      context: .
      dockerfile: src/services/proxy/Dockerfile
    ports:
      - 8001:8001
      - 8002:8002

  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: src/services/api/Dockerfile
    ports:
      - 5000:3000

  client:
    container_name: client
    restart: always
    build:
      context: .
      dockerfile: src/services/client/Dockerfile
    ports:
      - 5001:80
