version: '3.7'


volumes:
  mongo:
    driver: local
  elasticsearch:
    driver: local  


services:
  # elasticsearch:
  #   container_name: elasticsearch
  #   restart: always
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - elasticsearch:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300

  # kibana:
  #   container_name: kibana
  #   restart: always
  #   image: docker.elastic.co/kibana/kibana:7.8.1
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch

  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PSWD}
    volumes:
      - mongo:/data/db/
    ports:
      - 27017:27017
    depends_on:
    #   - elasticsearch

  proxy:
    container_name: proxy
    restart: always
    build:
      context: .
      dockerfile: src/services/proxy/Dockerfile
    ports:
      - 8001:8001
      - 8002:8002

  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: src/services/api/Dockerfile
    ports:
      - 5000:3000
    depends_on:
      - proxy
      - mongo
      # - elasticsearch

  client:
    container_name: client
    restart: always
    build:
      context: .
      dockerfile: src/services/client/Dockerfile
    ports:
      - 5001:80
    depends_on:
      - api
