version = 0.1

[[task]]
name = 'build'
run = 'rimraf ./dist && rollup --config rollup.config.js'

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = 'ncu -u'

[[task]]
name = 'publish:major'
env = { TC = 'utc'}
run = '''
  chomp build
  node ../../../scripts/publish.js -p  @saeon/logger -s major
'''

[[task]]
name = 'publish:minor'
env = { TC = 'utc'}
run = '''
  chomp build
  node ../../../scripts/publish.js -p  @saeon/logger -s minor
'''

[[task]]
name = 'publish:patch'
env = { TC = 'utc'}
run = '''
  chomp build && TC=utc node ../../../scripts/publish.js -p  @saeon/logger -s patch
'''
