version = 0.1
default-task = 'start'

[[task]]
name = 'build'
run = 'rimraf ./dist && NODE_ENV=production webpack --config webpack/index.js'

[[task]]
name = 'lint'
run = 'eslint -c .eslintrc.cjs "src/**/*.{js,jsx}"'

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = 'ncu -u'

[[task]]
name = 'start'
env = { NODE_ENV="development" }
run = """
  rimraf ./dist \
  && onchange \
    "src/**/*.@(js|jsx|ts|tsx|css|scss)" \
    "../packages/logger/dist/**/*.@(js|jsx|ts|tsx)" \
    -- prettier --write {{changed}} \
    & webpack serve --port 3001 --config webpack/index.js
  """


[[task]]
name = 'reset'
run = """
rm -rf node_modules
find . \
  -name node_modules \
  -type d \
  -exec rm -rv {} + \
    && find . \
      -name package-lock.json \
      -type f \
      -delete
"""