version = 0.1

[[task]]
name = 'build'
run = 'rimraf ./dist && NODE_ENV=production webpack --config webpack/index.js'

[[task]]
name = 'lint'
run = 'eslint -c .eslintrc.cjs "src/**/*.{js,jsx}"'

[[task]]
name = 'ncu'
run = 'ncu -x react-router,react-router-dom'

[[task]]
name = 'ncu -u'
run = 'ncu -u -x react-router,react-router-dom'

[[task]]
name = 'start'
env = { NODE_ENV="development" }
run = """
  rimraf ./dist \
  && onchange \
    "src/**/*.@(js|jsx|ts|tsx|css|scss)" \
    "../packages/logger/dist/**/*.@(js|jsx|ts|tsx)" \
    -- prettier --write {{changed}} \
    & webpack serve --port 3001 --config webpack/index.js
  """

