version = 0.1

[[task]]
name = 'init:cli'
run = '''
  chmod +x env.sh
  source env.sh
'''

[[task]]
name = 'lint'
run = 'eslint -c .eslintrc.cjs "src/**/*.{js,mjs,cjs}"'

[[task]]
name = 'ncu'
run = 'ncu -x es8.1'

[[task]]
name = 'ncu:u'
run = 'ncu -u -x es8.1'

[[task]]
name = 'start'
env = { NODE_ENV = 'development', TZ = 'utc', NODE_TLS_REJECT_UNAUTHORIZED='0' }
run = """
  nodemon \
    --ext js,graphql,json \
    --watch ./src \
    --exec 'node --trace-warnings --experimental-json-modules src'
"""

[[task]]
name = 'prettier'
run = 'prettier --write "./**/*.@(js|jsx|json|mjs|cjs|graphql|yml)"'