version = 0.1

[[task]]
name = 'build'
run = 'rm -rf dist && rollup --config rollup.config.js'

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = 'ncu -u'

[[task]]
name = 'prettier:watch'
run = 'onchange "src/**/*.@(js|jsx|css|scss)" -- prettier --write {{changed}}'

[[task]]
name = 'publish:major'
env = { TC='utc' }
deps = ['build']
run = 'node ../../../scripts/publish.js -p @saeon/cli-tools -s major'

[[task]]
name = 'publish:minor'
env = { TC='utc' }
deps = ['build']
run = 'node ../../../scripts/publish.js -p @saeon/cli-tools -s minor'

[[task]]
name = 'publish:patch'
env = { TC='utc' }
deps = ['build']
run = 'node ../../../scripts/publish.js -p @saeon/cli-tools -s patch'
