version = 0.1

[[task]]
name = 'build'
run = 'npm run client-scenarios'

[[task]]
name = 'client-scenarios'
run = 'sudo chmod -R 777 dist/ && docker run --rm -it -v $(pwd):/opt/mermaid minlag/mermaid-cli:latest -C /opt/mermaid/style.css -c /opt/mermaid/config.json -i /opt/mermaid/src/client-scenarios.mmd -o /opt/mermaid/dist/client-scenarios.png'
