version = 0.1
default-task = 'start'

extensions = ['chomp@0.1:prettier']

[[task]]
name = 'init:cli'
run = '''
  chmod +x env.sh
  source env.sh
'''

[[task]]
name = 'lint'
run = 'eslint -c .eslintrc.cjs "src/**/*.{js,mjs,cjs}"'

[[task]]
name = 'ncu'
run = 'ncu -x es8.x,koa-passport,openid-client'

[[task]]
name = 'ncu:u'
run = 'ncu -u -x es8.x,koa-passport,openid-client'

[[task]]
name = 'start'
env = { NODE_ENV = 'development', TZ = 'utc', NODE_TLS_REJECT_UNAUTHORIZED='0' }
deps = [
    'src/**/*'
]
serial = true
run = """
node \
  --trace-warnings \
  --experimental-json-modules \
  src
"""

[[task]]
name = 'prettier'
targets = []
deps = []
invalidation = 'always'
run = 'prettier --cache --cache-strategy metadata --loglevel warn --ignore-path .prettierignore --write "src/**/*.@(js|jsx|json|mjs|cjs|graphql|yml)"'

[[task]]
name = 'reset'
run = """
rm -rf node_modules
find . \
  -name node_modules \
  -type d \
  -exec rm -rv {} + \
    && find . \
      -name package-lock.json \
      -type f \
      -delete
"""