name: DEV

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    
    - uses: actions/checkout@v1
      with:
        ref: master
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive

    # - name: Configure the server
    #   run: |
    #     sudo /opt/copy-main-nginx-conf.sh # This script contains this command: cp ./nginx/nginx.conf /etc/nginx/nginx.conf
    #     sudo /opt/copy-nginx-vhosts.sh # This script contains this command: cp ./nginx/vhosts/* /etc/nginx/conf.d/
    #     sudo /opt/restart-nginx.sh # This script contains this command: service nginx restart