name: DEV

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Configure services/anyproxy
        run: |
          echo "TODO -> SAEON_SPATIALDATA_PROXY=https://spatialdata.saeon.ac.za src/services/anyproxy/.env"

      - name: Configure services/atlas-api
        run: |
          echo "ALLOWED_ORIGINS=https://atlas.saeon.ac.za,https://api.atlas.saeon.ac.za" > src/services/atlas-api/.env
          echo "HTTP_PROXY=http://atlas-anyproxy-dev:8001" >> src/services/atlas-api/.env
          echo "GQL_PROVIDER=https://api.atlas.saeon.ac.za" >> src/services/atlas-api/.env
          echo "MONGO_URL=mongodb://atlas-mongodb-dev:27017" >> src/services/atlas-api/.env
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> src/services/atlas-api/.env
          echo "MONGO_PSWD=${{ secrets.MONGO_PSWD }}" >> src/services/atlas-api/.env

      - name: Configure services/atlas-client
        run: |
          echo "ATLAS_API_ADDRESS=https://api.atlas.saeon.ac.za" > src/services/atlas-client/.env
          echo "GQL_PROVIDER=https://api.atlas.saeon.ac.za/graphql" >> src/services/atlas-client/.env
          echo "GQL_SUBSCRIPTIONS_PROVIDER=wss://api.atlas.saeon.ac.za/graphql" >> src/services/atlas-client/.env
          echo "REDIRECT_URL=https://atlas.saeon.ac.za/authenticated" >> src/services/atlas-client/.env
          echo "DEFAULT_WARNING=Please note that this service, although available for general comment, is not live. For more information contact zach@saeon.ac.za" >> src/services/atlas-client/.env

      - name: Configure Nginx (server entry)
        run: |
          sudo /opt/copy-nginx-vhosts.sh # This script contains this command: cp ./nginx/vhosts/* /etc/nginx/conf.d/
          sudo /opt/reload-nginx.sh # This script contains this command: service nginx reload

      - name: Deploy services
        run: |
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" > ./.env
          echo "MONGO_PSWD=${{ secrets.MONGO_PSWD }}" >> ./.env
          /usr/local/bin/docker-compose up -d --force-recreate --build
