name: deployment@next

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: catalogue.saeon.dvn
    steps:
      - uses: actions/checkout@v2
        with:
          ref: next

      - name: Configure Nginx (server entry)
        run: |
          sudo /opt/copy-nginx-config.sh # cp ./platform-configuration/nginx/next/nginx.conf /etc/nginx/
          sudo /opt/copy-nginx-server-blocks.sh # cp ./platform-configuration/nginx/next/server-blocks/* /etc/nginx/conf.d/
          sudo /opt/reload-nginx.sh # service nginx reload

      - name: Deploy services
        run: >-
          CATALOGUE_API_ODP_CLIENT_SECRET="${{ secrets.CATALOGUE_API_ODP_CLIENT_SECRET_NEXT }}"
          MONGO_DB_ADDRESS="mongodb://mongo:27017"
          MONGO_DB_USERNAME="${{ secrets.MONGO_DB_USERNAME }}"
          MONGO_DB_PASSWORD="${{ secrets.MONGO_DB_PASSWORD }}"
          POSTGIS_HOST="postgis"
          POSTGIS_PORT="5432"
          POSTGIS_USERNAME="${{ secrets.POSTGIS_USERNAME }}"
          POSTGIS_PASSWORD="${{ secrets.POSTGIS_PASSWORD }}"
          ELASTICSEARCH_ADDRESS="http://elasticsearch:9200"
          CATALOGUE_LATEST_COMMIT=$(git rev-parse HEAD)
          CATALOGUE_DEPLOYMENT_ENV="development"
          CATALOGUE_PROXY_ADDRESS="http://proxy:8001"
          CATALOGUE_API_ADDRESS="https://api.catalogue.saeon.dvn"
          CATALOGUE_API_ALLOWED_ORIGINS="https://catalogue.saeon.dvn,https://api.catalogue.saeon.dvn"
          CATALOGUE_API_RESET_ELASTICSEARCH_INDEX="enabled"
          CATALOGUE_API_RESET_ELASTICSEARCH_TEMPLATE="enabled"
          CATALOGUE_API_GQL_ADDRESS="https://api.catalogue.saeon.dvn/graphql"
          CATALOGUE_API_GQL_SUBSCRIPTIONS_ADDRESS="wss://api.catalogue.saeon.dvn/graphql"
          CATALOGUE_CLIENT_AUTH_REDIRECT_URL="https://catalogue.saeon.dvn/authenticated"
          CATALOGUE_CLIENT_AUTH_ID="saeon-data-portal"
          CATALOGUE_CLIENT_AUTH_ENDPOINT="https://odp.saeon.ac.za/auth/oauth2/auth"
          CATALOGUE_CLIENT_AUTH_LOGOUT_ENDPOINT="https://odp.saeon.ac.za/auth/oauth2/sessions/logout"
          CATALOGUE_CLIENT_AUTH_TOKEN_ENDPOINT="https://odp.saeon.ac.za/auth/oauth2/token"
          CATALOGUE_CLIENT_AUTH_REQUESTED_SCOPES="ODP.Catalogue"
          CATALOGUE_CLIENT_AUTH=disabled
          CATALOGUE_CLIENT_ADDRESS="https://catalogue.saeon.dvn"
          CATALOGUE_CLIENT_DEFAULT_NOTICES="Welcome to the SAEON Catalogue!,info"
          /usr/local/bin/docker-compose --env-file docker-compose.env up -d --force-recreate --build