name: deployment@next

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: catalogue.saeon.dvn
    steps:
      - uses: actions/checkout@v2
        with:
          ref: next

      - name: Configure services
        run: |
          cp deployment-configs/next/odp-filter.js src/api/odp-filter.js
          cp deployment-configs/next/client-filters.json src/client/client-filters.json

      - name: Deploy services
        run: >-
          HOSTNAME="https://catalogue.saeon.dvn"
          ODP_FILTER_PATH="odp-filter.js"
          CATALOGUE_CLIENT_FILTER_CONFIG_PATH="client-filters.json"
          ODP_SSO_CLIENT_SECRET="${{ secrets.ODP_SSO_CLIENT_SECRET_NEXT}}"
          API_PUBLIC_ADDRESS="https://api.catalogue.saeon.dvn"
          CATALOGUE_CLIENT_PROXY_ADDRESS="https://proxy.saeon.dvn"
          ALLOWED_ORIGINS="https://catalogue.saeon.dvn,https://api.catalogue.saeon.dvn"
          CATALOGUE_API_CONTAINER_PORT_MAPPING=5000
          APP_KEY="${{ secrets.APP_KEY }}"
          NODE_ENV=production
          ODP_CLIENT_SECRET="${{ secrets.ODP_CLIENT_SECRET_NEXT }}"
          CATALOGUE_CLIENT_ADDRESS="https://catalogue.saeon.dvn"
          CATALOGUE_CLIENT_CONTAINER_PORT_MAPPING=5001
          CATALOGUE_CLIENT_DEFAULT_NOTICES="Welcome to the SAEON Catalogue!,info"
          DEPLOYMENT_ENV="development"
          LATEST_COMMIT=$(git rev-parse HEAD)
          MONGO_DB_PASSWORD="${{ secrets.MONGO_DB_PASSWORD }}"
          MONGO_DB_USERNAME="${{ secrets.MONGO_DB_USERNAME }}"
          ODP_ADDRESS="https://odp.saeon.dvn"
          POSTGIS_PASSWORD="${{ secrets.POSTGIS_PASSWORD }}"
          POSTGIS_USERNAME="${{ secrets.POSTGIS_USERNAME }}"
          NODE_TLS_REJECT_UNAUTHORIZED=0
          /usr/local/bin/docker-compose --env-file docker-compose.env up -d --force-recreate --build