name: deployment@next

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: catalogue.saeon.dvn
    steps:
      - uses: actions/checkout@v2
        with:
          ref: next

      - name: Configure services/proxy
        run: |
          echo "TODO -> SAEON_SPATIALDATA_PROXY=http://spatialdata.saeon.ac.za src/services/proxy/.env"

      - name: Configure services/api
        run: |
          echo "ALLOWED_ORIGINS=http://catalogue.saeon.dvn,http://api.catalogue.saeon.dvn" > src/services/api/.env
          echo "HTTP_PROXY=http://proxy:8001" >> src/services/api/.env
          echo "GQL_PROVIDER=http://api.catalogue.saeon.dvn" >> src/services/api/.env
          echo "MONGO_URL=mongodb://mongo:27017" >> src/services/api/.env
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> src/services/api/.env
          echo "MONGO_PSWD=${{ secrets.MONGO_PSWD }}" >> src/services/api/.env

      - name: Configure services/client
        run: |
          echo "CATALOGUE_API_ADDRESS=http://api.catalogue.saeon.dvn" > src/services/client/.env
          echo "GQL_PROVIDER=http://api.catalogue.saeon.dvn/graphql" >> src/services/client/.env
          echo "GQL_SUBSCRIPTIONS_PROVIDER=wss://api.catalogue.saeon.dvn/graphql" >> src/services/client/.env
          echo "REDIRECT_URL=http://catalogue.saeon.dvn/authenticated" >> src/services/client/.env
          echo "CLIENT_HOST_ADDRESS=http://catalogue.saeon.dvn" >> src/services/client/.env
          echo "DEFAULT_WARNING=This service is still under development - feedback and bug reports are welcome! Please contact zach@saeon.ac.za for more information" >> src/services/client/.env

      - name: Configure Nginx (server entry)
        run: |
          sudo /opt/copy-nginx-config.sh # cp ./server-config/nginx/next/nginx.conf /etc/nginx/
          sudo /opt/copy-nginx-server-blocks.sh # cp ./server-config/nginx/next/server-blocks/* /etc/nginx/conf.d/
          sudo /opt/reload-nginx.sh # service nginx reload

      - name: Deploy services
        run: |
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" > ./.env
          echo "MONGO_PSWD=${{ secrets.MONGO_PSWD }}" >> ./.env
          /usr/local/bin/docker-compose up -d --force-recreate --build
