name: deployment@next

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: catalogue.saeon.dvn
    steps:
      - uses: actions/checkout@v2
        with:
          ref: next

      - name: Configure Nginx (server entry)
        run: |
          sudo /opt/copy-nginx-config.sh # cp ./platform-configuration/nginx/next/nginx.conf /etc/nginx/
          sudo /opt/copy-nginx-server-blocks.sh # cp ./platform-configuration/nginx/next/server-blocks/* /etc/nginx/conf.d/
          sudo /opt/reload-nginx.sh # service nginx reload

      - name: Deploy services
        run: >-
          MONGO_DB_ADDRESS="mongodb://mongo:27017"
          MONGO_DB_USERNAME="${{ secrets.MONGO_DB_USERNAME }}"
          MONGO_DB_PASSWORD="${{ secrets.MONGO_DB_PASSWORD }}"
          POSTGIS_HOST="postgis"
          POSTGIS_PORT="5432"
          POSTGIS_USERNAME="${{ secrets.POSTGIS_USERNAME }}"
          POSTGIS_PASSWORD="${{ secrets.POSTGIS_PASSWORD }}"
          POSTGIS_FOREIGN_HOST="spatialdb.saeon.int"
          POSTGIS_FOREIGN_DB="BEA"
          POSTGIS_FOREIGN_USERNAME="${{ secrets.POSTGIS_FOREIGN_USERNAME }}"
          POSTGIS_FOREIGN_PASSWORD="${{ secrets.POSTGIS_FOREIGN_PASSWORD }}"
          ELASTICSEARCH_ADDRESS="http://elasticsearch:9200"
          CATALOGUE_LATEST_COMMIT=$(git rev-parse HEAD)
          CATALOGUE_DEPLOYMENT_ENV="development"
          CATALOGUE_PROXY_ADDRESS="http://proxy:8001"
          CATALOGUE_API_ADDRESS="http://api.catalogue.saeon.dvn"
          CATALOGUE_API_ALLOWED_ORIGINS="http://catalogue.saeon.dvn,http://api.catalogue.saeon.dvn"
          CATALOGUE_API_RESET_ELASTICSEARCH_INDEX="enabled"
          CATALOGUE_API_RESET_ELASTICSEARCH_TEMPLATE="enabled"
          CATALOGUE_API_RESET_POSTGIS="disabled"
          CATALOGUE_API_GQL_ADDRESS="http://api.catalogue.saeon.dvn/graphql"
          CATALOGUE_API_GQL_SUBSCRIPTIONS_ADDRESS="ws://api.catalogue.saeon.dvn/graphql"
          CATALOGUE_CLIENT_AUTH_REDIRECT_URL="http://catalogue.saeon.dvn/authenticated"
          CATALOGUE_CLIENT_ADDRESS="http://catalogue.saeon.dvn"
          CATALOGUE_CLIENT_DEFAULT_NOTICES="Welcome to the SAEON Catalogue!,info"
          /usr/local/bin/docker-compose --env-file docker-compose.env up -d --force-recreate --build