name: deployment@stable

on:
  push:
    branches:
      - stable

jobs:
  deploy:
    runs-on: catalogue.saeon.ac.za
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable  

      - name: Configure Nginx (server entry)
        run: |
          sudo /opt/copy-nginx-config.sh # cp ./platform-configuration/nginx/stable/nginx.conf /etc/nginx/
          sudo /opt/copy-nginx-server-blocks.sh # cp ./platform-configuration/nginx/stable/server-blocks/* /etc/nginx/conf.d/
          sudo /opt/reload-nginx.sh # service nginx reload

      - name: Deploy services
        run: >-
          MONGO_DB_ADDRESS="mongodb://mongo:27017"
          MONGO_DB_USERNAME="${{ secrets.MONGO_DB_USERNAME }}"
          MONGO_DB_PASSWORD="${{ secrets.MONGO_DB_PASSWORD }}"
          POSTGIS_HOST="postgis"
          POSTGIS_PORT="5432"
          POSTGIS_USERNAME="${{ secrets.POSTGIS_USERNAME }}"
          POSTGIS_PASSWORD="${{ secrets.POSTGIS_PASSWORD }}"
          POSTGIS_FOREIGN_HOST="spatialdb.saeon.int"
          POSTGIS_FOREIGN_DB="BEA"
          POSTGIS_FOREIGN_USERNAME="${{ secrets.POSTGIS_FOREIGN_USERNAME }}"
          POSTGIS_FOREIGN_PASSWORD="${{ secrets.POSTGIS_FOREIGN_PASSWORD }}"
          ELASTICSEARCH_ADDRESS="http://elasticsearch:9200"
          CATALOGUE_LATEST_COMMIT=$(git rev-parse HEAD)
          CATALOGUE_DEPLOYMENT_ENV="production"
          CATALOGUE_PROXY_ADDRESS="http://proxy:8001"
          CATALOGUE_API_ADDRESS="https://api.catalogue.saeon.ac.za"
          CATALOGUE_API_ALLOWED_ORIGINS="https://atlas.saeon.ac.za,https://catalogue.saeon.ac.za,https://api.catalogue.saeon.ac.za"
          CATALOGUE_API_RESET_ELASTICSEARCH_INDEX="enabled"
          CATALOGUE_API_RESET_ELASTICSEARCH_TEMPLATE="enabled"
          CATALOGUE_API_RESET_POSTGIS="disabled"
          CATALOGUE_API_GQL_ADDRESS="https://api.catalogue.saeon.ac.za/graphql"
          CATALOGUE_API_GQL_SUBSCRIPTIONS_ADDRESS="wss://api.catalogue.saeon.ac.za/graphql"
          CATALOGUE_CLIENT_AUTH_REDIRECT_URL="https://catalogue.saeon.ac.za/authenticated"
          CATALOGUE_CLIENT_ADDRESS="https://catalogue.saeon.ac.za"
          CATALOGUE_CLIENT_DEFAULT_NOTICES="Welcome to the SAEON Catalogue! Please note this software is still in beta,info"
          /usr/local/bin/docker-compose --env-file docker-compose.env up -d --force-recreate --build
