name: deployment@stable

on:
  push:
    branches:
      - stable

jobs:
  deploy:
    runs-on: catalogue.saeon.ac.za
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable  

      - name: Configure services/proxy
        run: |
          echo "ELASTICSEARCH_PROXY=http://elasticsearch.saeon.int" > src/services/proxy/.env
          echo "LATEST_COMMIT=`git rev-parse HEAD`" >> src/services/proxy/.env

      - name: Configure services/api
        run: |
          echo "ALLOWED_ORIGINS=https://atlas.saeon.ac.za,https://catalogue.saeon.ac.za,https://api.catalogue.saeon.ac.za" > src/services/api/.env
          echo "HTTP_PROXY=http://proxy:8001" >> src/services/api/.env
          echo "GQL_PROVIDER=https://api.atlas.saeon.ac.za" >> src/services/api/.env
          echo "ES_HOST_ADDRESS=http://elasticsearch:9200" >> src/services/api/.env
          echo "ES_TEMPLATE_INTEGRATION_ENABLED=disabled" >> src/services/api/.env
          echo "ES_INDEX_INTEGRATION_ENABLED=disabled" >> src/services/api/.env
          echo "DEPLOY_ENV=production" >> src/services/api/.env
          echo "MONGO_URL=mongodb://mongo:27017" >> src/services/api/.env
          echo "FORCE_PG_RESET=true" >> src/services/api/.env
          echo "POSTGIS_HOST=postgis" >> src/services/api/.env
          echo "POSTGIS_PORT=5432" >> src/services/api/.env
          echo "POSTGIS_FOREIGN_HOST=spatialdb.saeon.int" >> src/services/api/.env
          echo "POSTGIS_FOREIGN_DBNAME=BEA" >> src/services/api/.env
          echo "LATEST_COMMIT=`git rev-parse HEAD`" >> src/services/api/.env          
        

      - name: Configure services/client
        run: |
          echo "CATALOGUE_API_ADDRESS=https://api.atlas.saeon.ac.za" > src/services/client/.env
          echo "GQL_PROVIDER=https://api.atlas.saeon.ac.za/graphql" >> src/services/client/.env
          echo "GQL_SUBSCRIPTIONS_PROVIDER=wss://api.catalogue.saeon.ac.za/graphql" >> src/services/client/.env
          echo "REDIRECT_URL=https://catalogue.saeon.ac.za/authenticated" >> src/services/client/.env
          echo "CLIENT_HOST_ADDRESS=https://catalogue.saeon.ac.za" >> src/services/client/.env
          echo "DEPLOYMENT_ENV=production" >> src/services/client/.env
          echo "DEFAULT_NOTICES=Welcome to the SAEON metadata catalogue,info; Please note: this service is still under development,info;Feedback and bug reports are welcome! Please contact zach@saeon.ac.za for more information,info" >> src/services/client/.env
          echo "LATEST_COMMIT=`git rev-parse HEAD`" >> src/services/client/.env

      - name: Configure Nginx (server entry)
        run: |
          sudo /opt/copy-nginx-config.sh # cp ./platform-configuration/nginx/stable/nginx.conf /etc/nginx/
          sudo /opt/copy-nginx-server-blocks.sh # cp ./platform-configuration/nginx/stable/server-blocks/* /etc/nginx/conf.d/
          sudo /opt/reload-nginx.sh # service nginx reload

      - name: Deploy services
        run: |
          POSTGIS_FOREIGN_USER="${{ secrets.POSTGIS_FOREIGN_USER }}" POSTGIS_FOREIGN_PASSWORD="${{ secrets.POSTGIS_FOREIGN_PASSWORD }}" POSTGIS_USER="${{ secrets.POSTGIS_USER }}" POSTGIS_PSWD="${{ secrets.POSTGIS_PSWD }}" MONGO_USER="${{ secrets.MONGO_USER }}" MONGO_PSWD="${{ secrets.MONGO_PSWD }}" /usr/local/bin/docker-compose --env-file docker-compose.env up -d --force-recreate --build
