name: deploy@stable

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: saeon/sdp-stable-api
  INTERNAL_CLIENTS_IMAGE_NAME: saeon/sdp-stable-clients-int
  PUBLIC_CLIENTS_IMAGE_NAME: saeon/sdp-stable-clients-pub
  BRANCH_REF: stable
  CURATOR_CONTACT: curation@saeon.nrf.ac.za
  TECHNICAL_CONTACT: development@saeon.nrf.ac.za
  DEFAULT_ADMIN_EMAIL_ADDRESSES: pl.chiloane@saeon.nrf.ac.za,cl.davisreddy@saeon.nrf.ac.za
  DEFAULT_SYSADMIN_EMAIL_ADDRESSES: zd.smith@saeon.nrf.ac.za

jobs:
  build-api:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Check out source code (shared)
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Configure ODP integration filter
        run: |
          cp deploy/stable/config/odp-filter.js src/api/odp-filter.js

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: src/api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-internal-clients:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Check out source code (shared)
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Configure internal client UI filters
        run: |
          cp deploy/stable/config/client-filters.json src/clients/client-filters.json

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.INTERNAL_CLIENTS_IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push internal clients
        uses: docker/build-push-action@v2
        with:
          context: src/clients
          build-args: |
            API_ADDRESS=https://api.catalogue.saeon.ac.za
            CATALOGUE_NGINX_SERVER_NAME=catalogue.saeon.ac.za
            CLIENTS_DEFAULT_NOTICES='Welcome to the SAEON Catalogue!,info'
            CLIENTS_PUBLIC_ADDRESS=https://catalogue.saeon.ac.za
            CLIENTS_SEARCH_FILTER_CONFIG_PATH=client-filters.json
            CURATOR_CONTACT=${{ env.CURATOR_CONTACT }}
            TECHNICAL_CONTACT=${{ env.TECHNICAL_CONTACT }}
            DEPLOYMENT_ENV=production
            PROXY_ADDRESS=https://proxy.saeon.ac.za
            NGINX_SERVER_BLOCK=nginx/clients-internal.conf
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-public-clients:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Check out source code (shared)
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Configure public client UI filters
        run: |
          cp deploy/stable/config/client-filters.json src/clients/client-filters.json

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.PUBLIC_CLIENTS_IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push public clients
        uses: docker/build-push-action@v2
        with:
          context: src/clients
          build-args: |
            API_ADDRESS=https://api.catalogue.saeon.ac.za
            CATALOGUE_NGINX_SERVER_NAME=catalogue.saeon.ac.za
            CLIENTS_DEFAULT_NOTICES='Welcome to the SAEON Catalogue!,info'
            CLIENTS_PUBLIC_ADDRESS=https://catalogue.saeon.ac.za
            CLIENTS_SEARCH_FILTER_CONFIG_PATH=client-filters.json
            DEPLOYMENT_ENV=production
            CURATOR_CONTACT=${{ env.CURATOR_CONTACT }}
            TECHNICAL_CONTACT=${{ env.TECHNICAL_CONTACT }}
            PROXY_ADDRESS=https://proxy.saeon.ac.za
            NGINX_SERVER_BLOCK=nginx/clients-public.conf
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [build-api, build-internal-clients, build-public-clients]
    runs-on: github-runner.saeon.int
    steps:
      - name: Check out source code (shared)
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: (SCP) Copy stack configuration to app server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOSTNAME }}
          username: ${{ secrets.DEPLOYMENT_HOST_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_HOST_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_HOST_SSH_PORT }}
          source: 'deploy/stable/stack.yml'
          target: 'sdp-stable'

      - name: (SSH) Deploy stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOSTNAME }}
          username: ${{ secrets.DEPLOYMENT_HOST_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_HOST_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_HOST_SSH_PORT }}
          script: |
            echo "API_IMAGE=${{ needs.build-api.outputs.image }}" > /home/runner/sdp-stable/deploy/stable/stack.env
            echo "INTERNAL_CLIENTS_IMAGE=${{ needs.build-internal-clients.outputs.image }}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            echo "PUBLIC_CLIENTS_IMAGE=${{ needs.build-public-clients.outputs.image }}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            echo "APP_KEY=${{ secrets.APP_KEY }}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            echo "MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            echo "MONGO_DB_USERNAME=${{ secrets.MONGO_DB_USERNAME }}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            echo "ODP_CLIENT_SECRET=${{ secrets.ODP_CLIENT_SECRET }}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            echo "ODP_SSO_CLIENT_SECRET=${{ secrets.ODP_SSO_CLIENT_SECRET}}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            echo "CURATOR_CONTACT=${{ env.CURATOR_CONTACT }}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            echo "TECHNICAL_CONTACT=${{ env.TECHNICAL_CONTACT }}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            echo "DEFAULT_ADMIN_EMAIL_ADDRESSES=${{ env.DEFAULT_ADMIN_EMAIL_ADDRESSES }}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            echo "DEFAULT_SYSADMIN_EMAIL_ADDRESSES=${{ env.DEFAULT_SYSADMIN_EMAIL_ADDRESSES }}" >> /home/runner/sdp-stable/deploy/stable/stack.env
            sudo /opt/deploy-docker-stack.sh /home/runner/sdp-stable/deploy/stable/stack.yml /home/runner/sdp-stable/deploy/stable/stack.env sdp_stable
