name: deployment@next

on:
  pull_request:
    branches:
      - next

jobs:
  deploy:
    runs-on: catalogue.saeon.dvn
    steps:
      - uses: actions/checkout@v2
        with:
          ref: next

      - name: Test
        run: |
          echo hello